name: env_fastai
channels:
  - fastchan
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - fastai=2.7.12
  - jupyterlab=4.2.1
  - ipympl=0.9.4
  - h5py=3.11.0
  - nbdev=2.3.12
  - seaborn=0.13.2
  - pip:
      - ray[tune]==2.23